// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psbqxcjukxlbwjjanuci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzYnF4Y2p1a3hsYndqamFudWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjAxMTcsImV4cCI6MjA2NjIzNjExN30.kT2lGcV9lcTYBEyQJxKMdxCrw17zQI0XUenHrZ8EVrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);